spring.application.name=SuperOdette
spring.datasource.url=jdbc:postgresql://ep-little-pine-aiyxzztj-pooler.c-4.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OMrbuD5wsN9T
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=hopeful-osprey-38290.upstash.io
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=AZWSAAIncDFlMzI0YzVlOTIyNGI0M2JlYTMyZGFhODA2YzVhMmRiOHAxMzgyOTA
spring.data.redis.ssl.enabled=true
spring.main.lazy-initialization=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

jwt.secret=seu_segredo_super_secreto_aqui
jwt.expiration=86400000