spring.application.name=${APP_NAME:SuperOdette}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/neondb}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:redis_password}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

spring.main.lazy-initialization=${LAZY_INIT:true}

spring.jpa.hibernate.ddl-auto=${JPA_DDL:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=${LOB_CREATION:true}
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl